baseURL: "https://litepali.com"
languageCode: "en-us"
title: "LitePali - Lightweight ColPali-based retrieval"
theme: "PaperMod"

params:
  description: "LitePali is a minimalist, efficient implementation of ColPali for image retrieval and indexing, optimized for cloud deployment."
  author: "Simeon Emanuilov"
  images: ["/assets/logo.png"]

  profileMode:
    enabled: true
    title: "LitePali"
    subtitle: "Efficient Image Retrieval"
    imageUrl: "/assets/logo.png"
    imageTitle: "LitePali Logo"
    buttons:
      - name: Docs
        url: "/docs"
      - name: GitHub
        url: "https://github.com/s-emanuilov/litepali"

  socialIcons:
    - name: "github"
      url: "https://github.com/s-emanuilov"
    - name: "twitter"
      url: "https://twitter.com/s_emanuilov"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/simeon-emanuilov/"
    - name: "googlescholar"
      url: "https://scholar.google.bg/citations?user=clJUDxcAAAAJ&hl=en&oi=ao"

  # Add GitHub-specific metadata
  github:
    repo: "s-emanuilov/litepali"
    countStars: true
    countForks: true


# Enable syntax highlighting
pygmentsUseClasses: true
pygmentsCodeFences: true

# Enable tags and categories
taxonomies:
  tag: "tags"
  category: "categories"
