title: "LitePali - Lightweight ColPali-based retrieval"
description: "LitePali is a minimalist, efficient implementation of ColPali for image retrieval and indexing, optimized for cloud deployment."
theme: minima

author:
  name: "Simeon Emanuilov"
  email: "simeon.emanuilov@gmail.com"

social_links:
  github: s-emanuilov
  twitter: s_emanuilov
  linkedin: simeon-emanuilov

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
